/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author skees
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController Controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        this.Controller = new AgendaController(this);
        //Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        TextHora = new javax.swing.JTextField();
        Observacoes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        BotaoAgendar = new javax.swing.JButton();
        Cliente = new javax.swing.JLabel();
        BoxServico = new javax.swing.JComboBox<>();
        Servico = new javax.swing.JLabel();
        BoxCliente = new javax.swing.JComboBox<>();
        Valor = new javax.swing.JLabel();
        TexteID = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        TextData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAgendamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(754, 454));
        setPreferredSize(new java.awt.Dimension(754, 474));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        TextHora.setBackground(new java.awt.Color(255, 255, 255));
        TextHora.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextHora.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 170, 30));

        Observacoes.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Observacoes.setForeground(new java.awt.Color(255, 255, 255));
        Observacoes.setText("Observações");
        getContentPane().add(Observacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        TextObservacao.setBackground(new java.awt.Color(255, 255, 255));
        TextObservacao.setColumns(20);
        TextObservacao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextObservacao.setForeground(new java.awt.Color(0, 0, 0));
        TextObservacao.setRows(5);
        jScrollPane2.setViewportView(TextObservacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 280, 150));

        BotaoAgendar.setBackground(new java.awt.Color(0, 204, 51));
        BotaoAgendar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BotaoAgendar.setForeground(new java.awt.Color(0, 0, 0));
        BotaoAgendar.setText("Agendar");
        BotaoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 280, 30));

        Cliente.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cliente");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, -1));

        BoxServico.setBackground(new java.awt.Color(255, 255, 255));
        BoxServico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BoxServico.setForeground(new java.awt.Color(0, 0, 0));
        BoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(BoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 30));

        Servico.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Servico.setForeground(new java.awt.Color(255, 255, 255));
        Servico.setText("Serviço");
        getContentPane().add(Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        BoxCliente.setBackground(new java.awt.Color(255, 255, 255));
        BoxCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BoxCliente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(BoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        Valor.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor R$");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, -1));

        TexteID.setBackground(new java.awt.Color(255, 255, 255));
        TexteID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TexteID.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TexteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, 30));

        Data.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 70, -1));

        TextValor.setBackground(new java.awt.Color(255, 255, 255));
        TextValor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextValor.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 30));

        Hora.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, -1));

        TextData.setBackground(new java.awt.Color(255, 255, 255));
        TextData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextData.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 30));

        TabelaAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        TabelaAgendamentos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TabelaAgendamentos.setForeground(new java.awt.Color(0, 0, 0));
        TabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAgendamentos.setShowGrid(true);
        jScrollPane1.setViewportView(TabelaAgendamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 540, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void BoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxServicoItemStateChanged
        // Atualiza sempre que que seleciona um item:
        this.Controller.atualizaValor();
    }//GEN-LAST:event_BoxServicoItemStateChanged

    private void BotaoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarActionPerformed
        // AAdiciona na agenda de eventos:
        this.Controller.Agendar();
    }//GEN-LAST:event_BotaoAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAgendar;
    private javax.swing.JComboBox<String> BoxCliente;
    private javax.swing.JComboBox<String> BoxServico;
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Observacoes;
    private javax.swing.JLabel Servico;
    private javax.swing.JTable TabelaAgendamentos;
    private javax.swing.JTextField TextData;
    private javax.swing.JTextField TextHora;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JTextField TexteID;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void Iniciar() {
        this.Controller.atualizaTabela();
        this.Controller.atualizaCliente();
        this.Controller.atualizaServico();
        this.Controller.atualizaValor();
    }

    public JTable getTabelaAgendamentos() {
        return TabelaAgendamentos;
    }

    public void setTabelaAgendamentos(JTable TabelaAgendamentos) {
        this.TabelaAgendamentos = TabelaAgendamentos;
    }

    public JComboBox<String> getBoxCliente() {
        return BoxCliente;
    }

    public void setBoxCliente(JComboBox<String> BoxCliente) {
        this.BoxCliente = BoxCliente;
    }

    public JComboBox<String> getBoxServico() {
        return BoxServico;
    }

    public void setBoxServico(JComboBox<String> BoxServico) {
        this.BoxServico = BoxServico;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTexteID() {
        return TexteID;
    }

    public void setTexteID(JTextField TexteID) {
        this.TexteID = TexteID;
    }

    public JTextField getTextData() {
        return TextData;
    }

    public void setTextData(JTextField TextData) {
        this.TextData = TextData;
    }

    public JTextField getTextHora() {
        return TextHora;
    }

    public void setTextHora(JTextField TextHora) {
        this.TextHora = TextHora;
    }

    public JTextArea getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao) {
        this.TextObservacao = TextObservacao;
    }

    

}
