/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteController;
import Model.Cliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author skees
 */
public class ClienteView extends javax.swing.JFrame {

    
    private final ClienteController Controller;
    /**
     * Creates new form Cliente
     */
    public ClienteView() {
        initComponents();
        this.Controller = new ClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TextNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextRG = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextCep = new javax.swing.JTextField();
        BotaoCadatrarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        TextNome.setBackground(new java.awt.Color(255, 255, 255));
        TextNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNome.setForeground(new java.awt.Color(0, 0, 0));
        TextNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 230, 30));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        BoxSexo.setBackground(new java.awt.Color(255, 255, 255));
        BoxSexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoxSexo.setForeground(new java.awt.Color(0, 0, 0));
        BoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma das opções", "M", "F", " " }));
        getContentPane().add(BoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, 30));

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data de Nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        TextNascimento.setBackground(new java.awt.Color(255, 255, 255));
        TextNascimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNascimento.setForeground(new java.awt.Color(0, 0, 0));
        TextNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 30));

        jLabel6.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        TextNumero.setBackground(new java.awt.Color(255, 255, 255));
        TextNumero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNumero.setForeground(new java.awt.Color(0, 0, 0));
        TextNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 30));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        TextRG.setBackground(new java.awt.Color(255, 255, 255));
        TextRG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextRG.setForeground(new java.awt.Color(0, 0, 0));
        TextRG.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 150, 30));

        jLabel8.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 30, -1));

        TextEmail.setBackground(new java.awt.Color(255, 255, 255));
        TextEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextEmail.setForeground(new java.awt.Color(0, 0, 0));
        TextEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 220, 30));

        jLabel9.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Endereço");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        TextEndereco.setBackground(new java.awt.Color(255, 255, 255));
        TextEndereco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextEndereco.setForeground(new java.awt.Color(0, 0, 0));
        TextEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 220, 30));

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEP");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        TextCep.setBackground(new java.awt.Color(255, 255, 255));
        TextCep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextCep.setForeground(new java.awt.Color(0, 0, 0));
        TextCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 150, 30));

        BotaoCadatrarCliente.setBackground(new java.awt.Color(0, 204, 0));
        BotaoCadatrarCliente.setFont(new java.awt.Font("Freehand521 BT", 0, 18)); // NOI18N
        BotaoCadatrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        BotaoCadatrarCliente.setText("Cadastrar");
        BotaoCadatrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadatrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadatrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/ClienteFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadatrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadatrarClienteActionPerformed
        try {
            // Chama a função para cadastrar cliente
            Controller.CadastrarCliente();
        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadatrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadatrarCliente;
    private javax.swing.JComboBox<String> BoxSexo;
    private javax.swing.JTextField TextCep;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextNascimento;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNumero;
    private javax.swing.JTextField TextRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getBoxSexo() {
        return BoxSexo;
    }

    public void setBoxSexo(JComboBox<String> BoxSexo) {
        this.BoxSexo = BoxSexo;
    }

    public JTextField getTextCep() {
        return TextCep;
    }

    public void setTextCep(JTextField TextCep) {
        this.TextCep = TextCep;
    }

    public JTextField getTextEmail() {
        return TextEmail;
    }

    public void setTextEmail(JTextField TextEmail) {
        this.TextEmail = TextEmail;
    }

    public JTextField getTextEndereco() {
        return TextEndereco;
    }

    public void setTextEndereco(JTextField TextEndereco) {
        this.TextEndereco = TextEndereco;
    }

    public JTextField getTextNascimento() {
        return TextNascimento;
    }

    public void setTextNascimento(JTextField TextNascimento) {
        this.TextNascimento = TextNascimento;
    }

    public JTextField getTextNome() {
        return TextNome;
    }

    public void setTextNome(JTextField TextNome) {
        this.TextNome = TextNome;
    }

    public JTextField getTextNumero() {
        return TextNumero;
    }

    public void setTextNumero(JTextField TextNumero) {
        this.TextNumero = TextNumero;
    }

    public JTextField getTextRG() {
        return TextRG;
    }

    public void setTextRG(JTextField TextRG) {
        this.TextRG = TextRG;
    }

    
}
