/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author skees
 */
public class UsuarioView extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public UsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        TextNascimento = new javax.swing.JTextField();
        TextNumero = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        BoxSexo = new javax.swing.JComboBox<>();
        TextNivelAcesso = new javax.swing.JTextField();
        TextRG = new javax.swing.JTextField();
        TextSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data de Nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 30, -1));

        jLabel9.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Senha");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nivel de Acesso");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        TextNome.setBackground(new java.awt.Color(255, 255, 255));
        TextNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 230, 30));

        TextNascimento.setBackground(new java.awt.Color(255, 255, 255));
        TextNascimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNascimento.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 30));

        TextNumero.setBackground(new java.awt.Color(255, 255, 255));
        TextNumero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNumero.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 230, 30));

        TextEmail.setBackground(new java.awt.Color(255, 255, 255));
        TextEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 230, 30));

        BoxSexo.setBackground(new java.awt.Color(255, 255, 255));
        BoxSexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoxSexo.setForeground(new java.awt.Color(0, 0, 0));
        BoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma das opões", "M", "F" }));
        getContentPane().add(BoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 62, 150, 30));

        TextNivelAcesso.setBackground(new java.awt.Color(255, 255, 255));
        TextNivelAcesso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextNivelAcesso.setForeground(new java.awt.Color(0, 0, 0));
        TextNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNivelAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(TextNivelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 90, 30));

        TextRG.setBackground(new java.awt.Color(255, 255, 255));
        TextRG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextRG.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 140, 30));

        TextSenha.setBackground(new java.awt.Color(255, 255, 255));
        TextSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextSenha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 140, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Freehand521 BT", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Usuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNivelAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxSexo;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextNascimento;
    private javax.swing.JTextField TextNivelAcesso;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNumero;
    private javax.swing.JTextField TextRG;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getBoxSexo() {
        return BoxSexo;
    }

    public void setBoxSexo(JComboBox<String> BoxSexo) {
        this.BoxSexo = BoxSexo;
    }

    public JTextField getTextEmail() {
        return TextEmail;
    }

    public void setTextEmail(JTextField TextEmail) {
        this.TextEmail = TextEmail;
    }

    public JTextField getTextNascimento() {
        return TextNascimento;
    }

    public void setTextNascimento(JTextField TextNascimento) {
        this.TextNascimento = TextNascimento;
    }

    public JTextField getTextNivelAcesso() {
        return TextNivelAcesso;
    }

    public void setTextNivelAcesso(JTextField TextNivelAcesso) {
        this.TextNivelAcesso = TextNivelAcesso;
    }

    public JTextField getTextNome() {
        return TextNome;
    }

    public void setTextNome(JTextField TextNome) {
        this.TextNome = TextNome;
    }

    public JTextField getTextNumero() {
        return TextNumero;
    }

    public void setTextNumero(JTextField TextNumero) {
        this.TextNumero = TextNumero;
    }

    public JTextField getTextRG() {
        return TextRG;
    }

    public void setTextRG(JTextField TextRG) {
        this.TextRG = TextRG;
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenha = TextSenha;
    }

    
    
}
